### ISSUE TITLE
Alignment off for some history touch on/off events

### ISSUE THREAD

**Issue by Plasma** [longzheng/mypal-ionic#20]
Slight design tweaks needed?

- [x] 'Darling station' has a blank line above it, compared to 'Flinders street station' below
- [x] The event number "1/" has a slash for some reason
- [ ] Also noticed the Hawthorn East route has a strange name, LR05_1_047

![img_5754](https://cloud.githubusercontent.com/assets/229209/22997376/3f6ced7c-f426-11e6-967e-db1337e3b5a5.PNG)

**Comment by longzheng** [comment]
First two bugs are the same zone layout issue, fixed in latest build.

Last issue is a string I'm getting from the site but I can see if I can better format.
