### ISSUE TITLE
Top up pass fails on iOS if inactive pass exists

### ISSUE THREAD

**Issue by richieshilton** [longzheng/mypal-ionic#44]
Top up money works, but top up pass fails on iOS

**Comment by longzheng** [comment]
Hmm, what sort of options did you set?

**Comment by richieshilton** [comment]
No options yet, after I click 'top up pass' the view disappears after a second and the popup appears saying 'error loading top up', 'top up feature is not available. Please check the mike website'

<img width="514" alt="screen shot 2017-04-01 at 4 48 00 pm" src="https://cloud.githubusercontent.com/assets/17777123/24575803/0409f8e0-16fb-11e7-88f0-fc7bb7031a2a.png">

**Comment by longzheng** [comment]
That's weird. Can you go to the myki site and try starting a top up pass, see if there's any errors?

**Comment by longzheng** [comment]
I just tested on both iOS and Android and loads fine for me. I suspect there might be something different with your card/account.

**Comment by richieshilton** [comment]
Ah my apologies, I checked on the myki site and as I already have an extra pass it caused an error. I didn't realise I had the extra pass! Thanks for the replies :)

**Comment by longzheng** [comment]
Oh that's very interesting, I would love to cater for that situation.

Can you help screenshot me what you see on the myki site for "pass inactive"?

**Comment by richieshilton** [comment]
No worries, the message is 'You have exceeded the maximum number of passes allowed on your myki.', screenshot attached

<img width="457" alt="screen shot 2017-04-01 at 7 26 00 pm" src="https://cloud.githubusercontent.com/assets/17777123/24577031/0d0d51d2-1712-11e7-896b-aa604d6e78c2.png">

**Comment by longzheng** [comment]
Can you also help screenshot your card's pass details like this?

![image](https://cloud.githubusercontent.com/assets/484912/24577227/a10cf7b8-1715-11e7-862c-37ebaf8f739f.png)

**Comment by richieshilton** [comment]
sure: 
<img width="430" alt="screen shot 2017-04-01 at 8 30 55 pm" src="https://cloud.githubusercontent.com/assets/17777123/24577480/2e62957e-171a-11e7-86be-c3faac47d8d3.png">
