### ISSUE TITLE
Negative balance showing as postive

### ISSUE THREAD

**Issue by Jason-Hendry** [longzheng/mypal-ionic#57]
Android Galaxy S8 version 1.0.26

**Comment by longzheng** [comment]
Hi Jason. Can I get a screenshot please.

![](http://stream1.gifsoup.com/view4/20150320/5186544/pretty-please-o.gif)

**Comment by longzheng** [comment]
@Jason-Hendry It would also be great to get a screenshot from your mymyki.com card overview and card details page (please black out sensitive information)

**Comment by Jason-Hendry** [comment]
Sorry for the delay

![image](https://user-images.githubusercontent.com/1018251/28810545-aa629b7a-76cd-11e7-9943-dd2f57caa4b8.png)
![screenshot_20170731-182940](https://user-images.githubusercontent.com/1018251/28810548-ac98bbc2-76cd-11e7-97fb-01becf6bc479.png)

**Comment by longzheng** [comment]
Thanks! That should be a simple fix.

**Comment by Jason-Hendry** [comment]
#58 That should do it
