### ISSUE TITLE
Android: dismiss Top Up Pass modal with Back button

### ISSUE THREAD

**Issue by Lx** [longzheng/mypal-ionic#68]
After opening the Top Up Pass modal, I expect to be able to dismiss it and return to the Balance screen by hitting my phone's Back button.  Instead, this causes the entire app to dismiss.

**Comment by longzheng** [comment]
I can't reproduce this with my Nexus 5 and Android 8. Pressing back with the top up modal always closes the modal.

The modal behaviour is provided by Ionic so I'm not doing anything special.
