### ISSUE TITLE
Allow multiple account logins

### ISSUE THREAD

**Issue by kierans** [longzheng/mypal-ionic#85]
I previously used the myUsage app to monitor my Myki accounts but the project seems to have been abandoned so I'm looking for an alternative.

One thing I found really useful was the ability to monitor/login to multiple Myki accounts for family members.

Is this possible?

**Comment by longzheng** [comment]
Due to the way the app is designed, it would be very difficult/impossible to allow multiple logins simultaneously since I can't maintain multiple HTTP cookies/sessions sets from the one app.

The best workaround is to log out/login using different accounts.
